#!/usr/bin/env bash
#
# export-participant-repo.sh — generate the participant-facing distribution
# repo from this maintainer repo.
#
# Usage:
#   ./export-participant-repo.sh [target-directory]
#
# Default target: ../nordicbike-agent-workshop-participant (sibling directory)
#
# What this does:
#   - Copies only the Participant tier of files (see README.md's Repository
#     Map / this script's PARTICIPANT_PATHS list below) into a brand-new
#     directory.
#   - Derives a participant-safe README.md from this repo's README.md by
#     stripping everything between <!-- PARTICIPANT-EXPORT:EXCLUDE-START -->
#     and <!-- PARTICIPANT-EXPORT:EXCLUDE-END --> marker pairs, rather than
#     hand-maintaining a second copy.
#   - git init's a FRESH repo at the target with no history from this repo,
#     so no prior commit can leak a facilitator-only file that was deleted
#     later. Never `git clone` this repo and delete files as an alternative
#     to this script — deleted files remain fully readable in git history.
#   - Never pushes anywhere and never touches any git remote. Review the
#     output, then push it yourself if it looks right.
#
# What is deliberately NOT copied (facilitator-only / maintainer-only):
#   evaluation/expected-results.md, evaluation/adversarial-cases.md,
#   facilitator-guide.md, presentation.md, updatenumbers.md,
#   export-participant-repo.sh (this script itself), spec.md (lives outside
#   this repo already), .git, .DS_Store.
#
# Re-run this before every session that hands the repo to participants —
# treat it the same way you'd treat updatenumbers.md: a repeatable step, not
# a one-time setup.

set -euo pipefail

SOURCE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TARGET_DIR="${1:-$SOURCE_DIR/../nordicbike-agent-workshop-participant}"

# Participant-tier paths, relative to SOURCE_DIR. Keep this list in sync with
# README.md's Repository Map — if you add a new top-level directory or file
# to the repo, decide its tier and add it here (or explicitly leave it out).
PARTICIPANT_PATHS=(
  "company"
  "products"
  "policies"
  "customers"
  "cases"
  "workshops"
  ".github"
  "evaluation/scoring-rubric.md"
)

if [ -e "$TARGET_DIR" ]; then
  echo "Error: target '$TARGET_DIR' already exists. Remove it or pick a different target, then re-run." >&2
  exit 1
fi

# Sanity-check the README's exclude markers are balanced before trusting
# them to strip anything. An unpaired marker is a sign someone edited
# README.md without noticing the markers — fail loudly rather than silently
# shipping either too much or a broken file.
starts=$(grep -c '<!-- PARTICIPANT-EXPORT:EXCLUDE-START -->' "$SOURCE_DIR/README.md" || true)
ends=$(grep -c '<!-- PARTICIPANT-EXPORT:EXCLUDE-END -->' "$SOURCE_DIR/README.md" || true)
if [ "$starts" -ne "$ends" ]; then
  echo "Error: README.md has $starts EXCLUDE-START markers but $ends EXCLUDE-END markers. Fix the markers before exporting." >&2
  exit 1
fi
if [ "$starts" -eq 0 ]; then
  echo "Warning: README.md has no PARTICIPANT-EXPORT markers at all — the participant README will be identical to the maintainer one. Check that's actually intended." >&2
fi

mkdir -p "$TARGET_DIR"

echo "Copying participant-tier content to $TARGET_DIR ..."
for path in "${PARTICIPANT_PATHS[@]}"; do
  src="$SOURCE_DIR/$path"
  if [ ! -e "$src" ]; then
    echo "Error: expected participant-tier path '$path' does not exist in $SOURCE_DIR. Aborting." >&2
    exit 1
  fi
  dest="$TARGET_DIR/$path"
  mkdir -p "$(dirname "$dest")"
  cp -R "$src" "$dest"
done

echo "Deriving participant README.md (stripping facilitator/maintainer-only spans) ..."
awk '
  /<!-- PARTICIPANT-EXPORT:EXCLUDE-START -->/ { skip=1; next }
  /<!-- PARTICIPANT-EXPORT:EXCLUDE-END -->/   { skip=0; next }
  skip { next }
  { print }
' "$SOURCE_DIR/README.md" > "$TARGET_DIR/README.md"

echo "Initializing a fresh git repo at $TARGET_DIR (no history carried over from the maintainer repo) ..."
SOURCE_COMMIT="$(git -C "$SOURCE_DIR" rev-parse --short HEAD 2>/dev/null || echo "unknown")"
(
  cd "$TARGET_DIR"
  git init -q
  git add -A
  git commit -q -m "Participant distribution — generated from maintainer repo @ $SOURCE_COMMIT

Generated by export-participant-repo.sh. Does not include:
evaluation/expected-results.md, evaluation/adversarial-cases.md,
facilitator-guide.md, presentation.md, updatenumbers.md."
)

echo ""
echo "Done. Participant repo ready at: $TARGET_DIR"
echo "Excluded (facilitator/maintainer-only, not present in this export):"
echo "  evaluation/expected-results.md"
echo "  evaluation/adversarial-cases.md"
echo "  facilitator-guide.md"
echo "  presentation.md"
echo "  updatenumbers.md"
echo ""
echo "Review the output before handing it to anyone or pushing it anywhere — this script never pushes to a remote itself."
