using System.Diagnostics;
using System.Net;
using System.Text.RegularExpressions;
using NordicBike.Portal;

var builder = WebApplication.CreateBuilder(args);
builder.Logging.ClearProviders();
builder.Logging.AddConsole();
builder.Logging.SetMinimumLevel(LogLevel.Information);
builder.Logging.AddFilter("Microsoft", LogLevel.Warning);
builder.Services.AddSingleton<PortalStore>();
var app = builder.Build();
app.UseStaticFiles();
app.Use(async (context, next) =>
{
	var correlation = context.Request.Headers["X-Correlation-ID"].FirstOrDefault() ?? Guid.NewGuid().ToString("N");
	context.Items["correlation"] = correlation; context.Response.Headers["X-Correlation-ID"] = correlation;
	var timer = Stopwatch.GetTimestamp(); await next();
	app.Logger.LogInformation("RequestCompleted {Method} {Path} {StatusCode} {ElapsedMs} {Role} {CorrelationId}", context.Request.Method, context.Request.Path, context.Response.StatusCode, Stopwatch.GetElapsedTime(timer).TotalMilliseconds, Role(context), correlation);
});

app.MapGet("/role/{role}", (HttpContext context, string role, string? returnTo) =>
{
	if (!PortalConfig.Roles.ContainsKey(role)) return Results.NotFound();
	context.Response.Cookies.Append("nb-role", role, new CookieOptions { IsEssential = true, SameSite = SameSiteMode.Lax });
	return Results.Redirect(string.IsNullOrWhiteSpace(returnTo) ? Landing(role) : returnTo);
});

app.MapGet("/api/health", (PortalStore store) => Results.Ok(new { status = "healthy", demoDate = DemoClock.Today, version = "1.0.0", store = "in-memory", orders = store.Orders.Count }));
app.MapGet("/api/products", (PortalStore store, string? q, string? category) => Results.Ok(store.Products.Where(item => (string.IsNullOrWhiteSpace(q) || item.Name.Contains(q, StringComparison.OrdinalIgnoreCase)) && (string.IsNullOrWhiteSpace(category) || item.Category == category))));
app.MapGet("/api/products/{id}", (PortalStore store, string id) => store.Products.SingleOrDefault(item => item.Id == id) is { } product ? Results.Ok(product) : Results.NotFound());
app.MapGet("/api/cart", (HttpContext context, PortalStore store) => Results.Ok(Cart(store, Customer(context))));
app.MapPost("/api/cart/items", async (HttpContext context, PortalStore store) =>
{
	var input = await context.Request.ReadFromJsonAsync<CartInput>(); var product = input is null ? null : store.Products.SingleOrDefault(item => item.Id == input.ProductId);
	if (input is null || product is null || input.Quantity < 1) return Problem("A product and positive quantity are required.", 400);
	var cart = store.Cart(Customer(context)); var existing = cart.SingleOrDefault(item => item.ProductId == input.ProductId && item.Configuration == input.Configuration);
	if (existing is null) cart.Add(new CartItem(Guid.NewGuid().ToString("N"), input.ProductId, input.Quantity, input.Configuration)); else { cart.Remove(existing); cart.Add(existing with { Quantity = existing.Quantity + input.Quantity }); }
	Audit(context, store, "Cart updated", "cart", product.Name); return Results.Created("/api/cart", Cart(store, Customer(context)));
});
app.MapMethods("/api/cart/items/{id}", ["PATCH"], async (HttpContext context, PortalStore store, string id) =>
{
	var input = await context.Request.ReadFromJsonAsync<CartInput>(); var cart = store.Cart(Customer(context)); var item = cart.SingleOrDefault(entry => entry.Id == id);
	if (item is null) return Results.NotFound(); if (input is null || input.Quantity < 1) return Problem("Quantity must be at least one.", 400);
	cart.Remove(item); cart.Add(item with { Quantity = input.Quantity }); Audit(context, store, "Cart quantity updated", "cart", id); return Results.Ok(Cart(store, Customer(context)));
});
app.MapDelete("/api/cart/items/{id}", (HttpContext context, PortalStore store, string id) =>
{
	var cart = store.Cart(Customer(context)); var item = cart.SingleOrDefault(entry => entry.Id == id); if (item is null) return Results.NotFound(); cart.Remove(item); Audit(context, store, "Cart item removed", "cart", id); return Results.NoContent();
});
app.MapPost("/api/orders", async (HttpContext context, PortalStore store) =>
{
	var input = await context.Request.ReadFromJsonAsync<CheckoutInput>(); var cart = store.Cart(Customer(context));
	if (input is null || string.IsNullOrWhiteSpace(input.Name) || string.IsNullOrWhiteSpace(input.Email) || string.IsNullOrWhiteSpace(input.City) || !input.IsSimulated || cart.Count == 0) return Problem("Name, email, delivery city, confirmation, and cart items are required.", 400);
	var lines = cart.Select(item => { var product = store.Products.Single(product => product.Id == item.ProductId); return new OrderLine(product.Id, product.Name, item.Quantity, product.Price, item.Configuration); }).ToList();
	var order = new Order { Id = store.NewOrderId(), CustomerId = Customer(context), Lines = lines, Status = "Confirmed", City = input.City, CreatedAt = DemoClock.Now, UpdatedAt = DemoClock.Now };
	order.Timeline.Add(new TimelineEvent(DemoClock.Now, "Order confirmed", "Your simulated order was accepted.")); store.Orders.Insert(0, order); cart.Clear(); Audit(context, store, "Checkout completed", order.Id, "Confirmed simulated order"); return Results.Created($"/api/orders/{order.Id}", ToOrder(order));
});
app.MapGet("/api/orders", (HttpContext context, PortalStore store) => Results.Ok(store.Orders.Where(order => Internal(context) || order.CustomerId == Customer(context)).OrderByDescending(order => order.CreatedAt).Select(ToOrder)));
app.MapGet("/api/orders/{id}", (HttpContext context, PortalStore store, string id) => store.Orders.SingleOrDefault(order => order.Id == id && (Internal(context) || order.CustomerId == Customer(context))) is { } order ? Results.Ok(ToOrder(order)) : Results.NotFound());
app.MapPost("/api/orders/{id}/return-requests", (HttpContext context, PortalStore store, string id) =>
{
	var order = store.Orders.SingleOrDefault(item => item.Id == id && item.CustomerId == Customer(context)); if (order is null) return Results.NotFound(); if (order.Status != "Delivered") return Problem("Only delivered orders can be returned.", 400);
	order.Status = "Return requested"; order.UpdatedAt = DemoClock.Now; order.Timeline.Add(new TimelineEvent(DemoClock.Now, "Return requested", "Support case created.")); var supportCase = NewCase(store, Customer(context), $"Return request for {id}", "Return request", "Please help me return this delivered order.", id, null); Audit(context, store, "Return requested", id, supportCase.Id); return Results.Ok(new { order = ToOrder(order), supportCaseId = supportCase.Id });
});
app.MapPost("/api/orders/{id}/advance", (HttpContext context, PortalStore store, string id) =>
{
	if (!Internal(context)) return Results.NotFound(); var order = store.Orders.SingleOrDefault(item => item.Id == id); if (order is null) return Results.NotFound(); var next = order.Status switch { "Confirmed" => "Processing", "Processing" => "Shipped", "Shipped" => "Delivered", _ => null }; if (next is null) return Problem("This order has no normal next fulfilment state.", 400);
	order.Status = next; order.UpdatedAt = DemoClock.Now; order.Tracking ??= next == "Shipped" ? "NBX-" + order.Id[^3..] : null; order.Timeline.Add(new TimelineEvent(DemoClock.Now, next, $"Order advanced to {next}.")); Audit(context, store, "Order status updated", id, next); return Results.Ok(ToOrder(order));
});
app.MapGet("/api/bikes", (HttpContext context, PortalStore store) => Results.Ok(store.Bikes.Where(bike => Internal(context) || bike.CustomerId == Customer(context))));
app.MapPost("/api/bikes/registrations", async (HttpContext context, PortalStore store) =>
{
	var input = await context.Request.ReadFromJsonAsync<BikeInput>(); var serial = input?.Serial ?? ""; if (input is null || input.Purchased == default || !Regex.IsMatch(serial, "^(AX3|FJC|VTP)-\\d{2}[AB]-\\d{5}$", RegexOptions.IgnoreCase)) return Problem("A valid NordicBike serial number and purchase date are required.", 400);
	var product = serial.StartsWith("AX3", StringComparison.OrdinalIgnoreCase) ? store.Products.Single(item => item.Id == "aurora-x3") : serial.StartsWith("FJC", StringComparison.OrdinalIgnoreCase) ? store.Products.Single(item => item.Id == "fjord-cargo") : store.Products.Single(item => item.Id == "vinter-pro");
	var bike = new Bike { Id = "BIKE-" + Guid.NewGuid().ToString("N")[..6].ToUpperInvariant(), CustomerId = Customer(context), ProductId = product.Id, ProductName = product.Name, Serial = serial.ToUpperInvariant(), Purchased = input.Purchased, Registration = "Pending verification", ServiceStatus = "Not assessed" }; store.Bikes.Add(bike); Audit(context, store, "Bike registration submitted", bike.Id, bike.Serial); return Results.Created($"/api/bikes/{bike.Id}", bike);
});
app.MapGet("/api/cases", (HttpContext context, PortalStore store, string? q, string? status) => Results.Ok(store.Cases.Where(item => (Internal(context) || item.CustomerId == Customer(context)) && (string.IsNullOrWhiteSpace(q) || Search(store, item).Contains(q, StringComparison.OrdinalIgnoreCase)) && (string.IsNullOrWhiteSpace(status) || item.Status == status)).Select(item => ToCase(store, item, Internal(context)))));
app.MapGet("/api/cases/{id}", (HttpContext context, PortalStore store, string id) => store.Cases.SingleOrDefault(item => item.Id == id && (Internal(context) || item.CustomerId == Customer(context))) is { } supportCase ? Results.Ok(ToCase(store, supportCase, Internal(context))) : Results.NotFound());
app.MapPost("/api/cases", async (HttpContext context, PortalStore store) =>
{
	var input = await context.Request.ReadFromJsonAsync<CaseInput>(); if (input is null || string.IsNullOrWhiteSpace(input.Subject) || string.IsNullOrWhiteSpace(input.Description) || string.IsNullOrWhiteSpace(input.Topic)) return Problem("Subject, description, and topic are required.", 400);
	var supportCase = NewCase(store, Customer(context), input.Subject, input.Topic, input.Description, input.OrderId, input.BikeId); Audit(context, store, "Support case created", supportCase.Id, input.Topic); return Results.Created($"/api/cases/{supportCase.Id}", ToCase(store, supportCase, false));
});
app.MapPost("/api/cases/{id}/messages", async (HttpContext context, PortalStore store, string id) =>
{
	var input = await context.Request.ReadFromJsonAsync<MessageInput>(); var supportCase = store.Cases.SingleOrDefault(item => item.Id == id && (Internal(context) || item.CustomerId == Customer(context))); if (supportCase is null) return Results.NotFound(); if (input is null || string.IsNullOrWhiteSpace(input.Body)) return Problem("Message body is required.", 400);
	var visibility = Internal(context) && input.Internal ? "Internal" : "Customer"; supportCase.Messages.Add(new CaseMessage(Actor(context), Role(context), visibility, input.Body.Trim(), DemoClock.Now)); supportCase.UpdatedAt = DemoClock.Now; supportCase.Timeline.Add(new TimelineEvent(DemoClock.Now, visibility == "Internal" ? "Internal note added" : "Message added", Actor(context))); Audit(context, store, visibility == "Internal" ? "Internal note added" : "Case message added", id, "Body redacted"); return Results.Ok(ToCase(store, supportCase, Internal(context)));
});
app.MapMethods("/api/cases/{id}", ["PATCH"], async (HttpContext context, PortalStore store, string id) =>
{
	if (!Internal(context)) return Results.NotFound(); var input = await context.Request.ReadFromJsonAsync<CaseUpdate>(); var supportCase = store.Cases.SingleOrDefault(item => item.Id == id); if (supportCase is null) return Results.NotFound(); if (input is null) return Problem("Update payload is required.", 400);
	if (!string.IsNullOrWhiteSpace(input.Status)) supportCase.Status = input.Status; if (!string.IsNullOrWhiteSpace(input.Priority)) supportCase.Priority = input.Priority; if (!string.IsNullOrWhiteSpace(input.Assignee)) supportCase.Assignee = input.Assignee; if (input.Escalated is not null) { if (supportCase.Escalated && !input.Escalated.Value && Role(context) != "Support lead") return Problem("Only a support lead can clear escalation.", 403); supportCase.Escalated = input.Escalated.Value; }
	supportCase.UpdatedAt = DemoClock.Now; supportCase.Timeline.Add(new TimelineEvent(DemoClock.Now, "Case updated", Actor(context))); Audit(context, store, "Case updated", id, "Fields updated"); return Results.Ok(ToCase(store, supportCase, true));
});
app.MapPost("/api/cases/{id}/service-requests", async (HttpContext context, PortalStore store, string id) =>
{
	if (!Internal(context)) return Results.NotFound(); var input = await context.Request.ReadFromJsonAsync<ServiceInput>(); var supportCase = store.Cases.SingleOrDefault(item => item.Id == id); if (supportCase is null) return Results.NotFound(); if (input is null || !new[] { "Stockholm", "Gothenburg", "Malmo" }.Contains(input.Center)) return Problem("A valid service center is required.", 400);
	var request = new ServiceRequest { Id = store.NewServiceId(), CaseId = id, Center = input.Center, State = "Awaiting item" }; store.ServiceRequests.Add(request); supportCase.Status = "Waiting for service center"; supportCase.Timeline.Add(new TimelineEvent(DemoClock.Now, "Service request created", $"{input.Center}; prepaid simulated label prepared.")); Audit(context, store, "Service request created", request.Id, input.Center); return Results.Created($"/api/service-requests/{request.Id}", request);
});
app.MapMethods("/api/service-requests/{id}", ["PATCH"], async (HttpContext context, PortalStore store, string id) =>
{
	if (!Internal(context)) return Results.NotFound(); var input = await context.Request.ReadFromJsonAsync<ServiceInput>(); var request = store.ServiceRequests.SingleOrDefault(item => item.Id == id); if (request is null) return Results.NotFound(); if (input is null || !PortalConfig.RepairStates.Contains(input.State ?? "")) return Problem("A valid repair state is required.", 400); request.State = input.State!; var supportCase = store.Cases.Single(item => item.Id == request.CaseId); supportCase.Timeline.Add(new TimelineEvent(DemoClock.Now, "Service request updated", request.State)); Audit(context, store, "Service request transitioned", id, request.State); return Results.Ok(request);
});
app.MapGet("/api/dashboard/support", (PortalStore store) => Results.Ok(new { open = store.Cases.Count(item => item.Status is not "Resolved" and not "Closed"), waitingForCustomer = store.Cases.Count(item => item.Status == "Waiting for customer"), escalated = store.Cases.Count(item => item.Escalated), averageFirstResponseHours = 3.4, byTopic = store.Cases.GroupBy(item => item.Topic).Select(group => new { topic = group.Key, count = group.Count() }) }));
app.MapGet("/api/dashboard/business", (PortalStore store) => Results.Ok(new { confirmedRevenue = store.Orders.Where(item => item.Status is not "Cancelled" and not "Returned").Sum(item => item.Total), statuses = store.Orders.GroupBy(item => item.Status).Select(group => new { status = group.Key, count = group.Count() }), returnRequests = store.Orders.Count(item => item.Status == "Return requested") }));
app.MapGet("/api/diagnostics/events", (HttpContext context, PortalStore store, string? correlationId, string? entityId) => !Internal(context) ? Results.NotFound() : Results.Ok(store.Audits.Where(item => (string.IsNullOrWhiteSpace(correlationId) || item.CorrelationId.Contains(correlationId, StringComparison.OrdinalIgnoreCase)) && (string.IsNullOrWhiteSpace(entityId) || item.EntityId.Contains(entityId, StringComparison.OrdinalIgnoreCase))).Take(50)));

app.MapGet("/", (HttpContext context) => Html(context, "Welcome", Home()));
app.MapGet("/shop", (HttpContext context, PortalStore store, string? q, string? category) => Html(context, "Shop", Shop(store, q, category)));
app.MapGet("/shop/{id}", (HttpContext context, PortalStore store, string id) => store.Products.SingleOrDefault(item => item.Id == id) is { } product ? Html(context, product.Name, ProductPage(product)) : Missing(context));
app.MapGet("/cart", (HttpContext context, PortalStore store) => Html(context, "Cart", CartPage(store, Customer(context))));
app.MapGet("/checkout", (HttpContext context, PortalStore store) => Html(context, "Checkout", Checkout(store, Customer(context))));
app.MapGet("/orders", (HttpContext context, PortalStore store) => Html(context, "Orders", OrdersPage(context, store)));
app.MapGet("/orders/{id}", (HttpContext context, PortalStore store, string id) => store.Orders.SingleOrDefault(item => item.Id == id && (Internal(context) || item.CustomerId == Customer(context))) is { } order ? Html(context, order.Id, OrderPage(context, order)) : Missing(context));
app.MapGet("/bikes", (HttpContext context, PortalStore store) => Html(context, "My bikes", BikesPage(context, store)));
app.MapGet("/support", (HttpContext context, PortalStore store, string? q, string? status) => Html(context, "Support", Internal(context) ? Queue(context, store, q, status) : CustomerSupport(context, store)));
app.MapGet("/support/{id}", (HttpContext context, PortalStore store, string id) => store.Cases.SingleOrDefault(item => item.Id == id && (Internal(context) || item.CustomerId == Customer(context))) is { } supportCase ? Html(context, supportCase.Id, CasePage(context, store, supportCase)) : Missing(context));
app.MapGet("/business", (HttpContext context, PortalStore store) => Internal(context) ? Html(context, "Business", Business(store)) : Missing(context));
app.MapGet("/diagnostics", (HttpContext context, PortalStore store, string? correlationId, string? entityId) => Internal(context) ? Html(context, "Diagnostics", Diagnostics(store, correlationId, entityId)) : Missing(context));
app.Logger.LogInformation("NordicBike Portal started. Demo roles: Anna Karlsson, Support agent, Support lead, Business operations.");
app.Run();

static string Key(HttpContext c) => c.Request.Cookies["nb-role"] is { } role && PortalConfig.Roles.ContainsKey(role) ? role : "anna";
static string Role(HttpContext c) => Key(c) switch { "support" => "Support agent", "lead" => "Support lead", "business" => "Business operations", _ => "Customer" };
static string Actor(HttpContext c) => PortalConfig.Roles[Key(c)].Name;
static string Customer(HttpContext c) => PortalConfig.Roles[Key(c)].Customer.Length > 0 ? PortalConfig.Roles[Key(c)].Customer : "NB-CUST-10041";
static bool Internal(HttpContext c) => Key(c) is "support" or "lead" or "business";
static string Landing(string key) => key is "support" or "lead" ? "/support" : key == "business" ? "/business" : "/shop";
static void Audit(HttpContext c, PortalStore s, string action, string id, string detail) { var correlation = c.Items["correlation"]?.ToString() ?? "unknown"; s.Audit(correlation, Actor(c), action, id, detail); c.RequestServices.GetRequiredService<ILoggerFactory>().CreateLogger("NordicBike.Domain").LogInformation("DomainEvent {Action} {EntityId} {Role} {CorrelationId}", action, id, Role(c), correlation); }
static IResult Problem(string detail, int status) => Results.Problem(detail: detail, statusCode: status, title: "Request could not be completed");
static object Cart(PortalStore s, string customer) { var lines = s.Cart(customer).Select(item => new { item.Id, item.Quantity, item.Configuration, product = s.Products.Single(product => product.Id == item.ProductId), total = s.Products.Single(product => product.Id == item.ProductId).Price * item.Quantity }); return new { items = lines, total = lines.Sum(item => item.total), delivery = 0m }; }
static object ToOrder(Order item) => new { item.Id, item.Status, item.City, item.CreatedAt, item.UpdatedAt, item.Tracking, item.Total, item.Lines, item.Timeline };
static object ToCase(PortalStore s, SupportCase item, bool internalView) => new { item.Id, customer = s.Customers.Single(customer => customer.Id == item.CustomerId), item.Subject, item.Description, item.Topic, item.Priority, item.Status, item.Assignee, item.Escalated, item.OrderId, item.BikeId, item.CreatedAt, item.UpdatedAt, messages = item.Messages.Where(message => internalView || message.Visibility == "Customer"), item.Timeline };
static SupportCase NewCase(PortalStore s, string customer, string subject, string topic, string description, string? order, string? bike) { var item = new SupportCase { Id = s.NewCaseId(), CustomerId = customer, Subject = subject.Trim(), Description = description.Trim(), Topic = topic, Priority = "Normal", Status = "New", Assignee = null, Escalated = false, OrderId = order, BikeId = bike, CreatedAt = DemoClock.Now, UpdatedAt = DemoClock.Now }; item.Messages.Add(new CaseMessage(s.Customers.Single(person => person.Id == customer).Name, "Customer", "Customer", description.Trim(), DemoClock.Now)); item.Timeline.Add(new TimelineEvent(DemoClock.Now, "Case created", topic)); s.Cases.Insert(0, item); return item; }
static string Search(PortalStore s, SupportCase item) => $"{item.Id} {item.Subject} {s.Customers.Single(customer => customer.Id == item.CustomerId).Name} {item.OrderId} {s.Bikes.SingleOrDefault(bike => bike.Id == item.BikeId)?.Serial}";
static string H(string? input) => WebUtility.HtmlEncode(input ?? "");
static string Date(DateTimeOffset at) => at.ToString("yyyy-MM-dd HH:mm");
static string Money(decimal amount) => $"{amount:N0} SEK";
static string Badge(string value) => $"<span class='badge'>{H(value)}</span>";
static string Events(IEnumerable<TimelineEvent> events) => string.Join("", events.OrderByDescending(item => item.At).Select(item => $"<div class='event'><time>{Date(item.At)}</time><b>{H(item.Title)}</b><span>{H(item.Detail)}</span></div>"));
static IResult Html(HttpContext c, string title, string body) => Results.Content($$"""<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{{H(title)}} | NordicBike</title><link rel="stylesheet" href="/site.css"></head><body><header><a class="brand" href="/">NORDIC<span>BIKE</span><small>AB / PORTAL</small></a><nav>{{(Internal(c) ? "<a href='/support'>Support</a><a href='/orders'>Orders</a><a href='/business'>Business</a><a href='/diagnostics'>Diagnostics</a>" : "<a href='/shop'>Shop</a><a href='/orders'>My orders</a><a href='/bikes'>My bikes</a><a href='/support'>Support</a><a href='/cart'>Cart</a>")}}</nav><details class="roles"><summary>{{H(Actor(c))}}</summary>{{string.Join("", PortalConfig.Roles.Select(role => $"<a href='/role/{role.Key}?returnTo={Uri.EscapeDataString(c.Request.Path + c.Request.QueryString)}'>{H(role.Value.Name)}</a>"))}}</details></header><main>{{body}}</main><footer>Demo date {{DemoClock.Today:yyyy-MM-dd}} <span>support@nordicbike.se · +46 8 555 123 00</span></footer><script src="/portal.js"></script></body></html>""", "text/html");
static IResult Missing(HttpContext c) => Html(c, "Not found", "<section class='empty'><p class='eyebrow'>404</p><h1>That route is not available here.</h1><a class='button' href='/shop'>Back to shop</a></section>");
static string Home() => "<section class='hero'><div><p class='eyebrow'>NORDICBIKE / EVERYDAY ELECTRIC</p><h1>Built for the long way home.</h1><p>Shop, track and get support through every season.</p><a class='button signal' href='/shop'>Explore the bikes</a></div><div class='hero-bike'><span>A</span><small>AURORA X3</small></div></section><section class='feature-row'><article><b>3</b><span>service centers</span></article><article><b>24</b><span>month bike warranty</span></article><article><b>1</b><span>place to manage your ride</span></article></section>";
static string Shop(PortalStore s, string? q, string? category) { var products = s.Products.Where(item => (string.IsNullOrWhiteSpace(q) || item.Name.Contains(q, StringComparison.OrdinalIgnoreCase)) && (string.IsNullOrWhiteSpace(category) || item.Category == category)); var filters = string.Join("", s.Products.Select(item => item.Category).Distinct().Select(item => $"<a class='filter {(item == category ? "active" : "")}' href='/shop?category={Uri.EscapeDataString(item)}'>{H(item)}</a>")); return $$"""<section class='page-head'><p class='eyebrow'>STORE / NORDIC CONDITIONS</p><h1>Find your everyday electric.</h1><form class='search'><input name='q' value='{{H(q)}}' placeholder='Search products'><button>Search</button></form><div class='filters'><a class='filter' href='/shop'>All</a>{{filters}}</div></section><section class='catalog'>{{string.Join("", products.Select(item => $"<article class='card'><div class='mark {item.Id}'>{H(item.Mark)}</div><p class='eyebrow'>{H(item.Category)}</p><h2>{H(item.Name)}</h2><p>{H(item.Description)}</p><div><strong>{Money(item.Price)}</strong><a class='link' href='/shop/{item.Id}'>Details</a></div></article>"))}}</section>"""; }
static string ProductPage(Product p) => $$"""<section class='product'><div class='mark large {{p.Id}}'>{{H(p.Mark)}}</div><div><p class='eyebrow'>{{H(p.Category)}}</p><h1>{{H(p.Name)}}</h1><p class='lead'>{{H(p.Description)}}</p><p class='spec'>{{H(p.Specs)}}</p><strong class='price'>{{Money(p.Price)}}</strong><form class='stack js-form' data-api='/api/cart/items' data-redirect='/cart'><input type='hidden' name='productId' value='{{p.Id}}'><input type='hidden' name='quantity' value='1'>{{(p.Options.Length == 0 ? "" : $"<label>Configuration<select name='configuration'>{string.Join("", p.Options.Select(option => $"<option>{H(option)}</option>"))}</select></label>")}}<button class='button'>Add to cart</button></form></div></section>""";
static string CartPage(PortalStore s, string customer) { var items = s.Cart(customer); if (items.Count == 0) return "<section class='empty'><p class='eyebrow'>YOUR CART</p><h1>Nothing is waiting yet.</h1><a class='button' href='/shop'>Browse products</a></section>"; var total = items.Sum(item => s.Products.Single(product => product.Id == item.ProductId).Price * item.Quantity); return $$"""<section class='page-head compact'><p class='eyebrow'>YOUR CART</p><h1>Ready when you are.</h1></section><section class='two'><article class='panel'>{{string.Join("", items.Select(item => { var product = s.Products.Single(product => product.Id == item.ProductId); return $"<div class='row'><span><b>{H(product.Name)}</b><small>{H(item.Configuration)}</small></span><span>{item.Quantity} × {Money(product.Price)}</span><b>{Money(product.Price * item.Quantity)}</b><button class='delete' data-api='/api/cart/items/{item.Id}'>×</button></div>"; }))}}</article><aside class='panel'><h2>Order summary</h2><div class='row'><span>Subtotal</span><b>{{Money(total)}}</b></div><div class='row'><span>Simulated delivery</span><b>0 SEK</b></div><div class='row total'><span>Total</span><b>{{Money(total)}}</b></div><a class='button' href='/checkout'>Continue to checkout</a></aside></section>"""; }
static string Checkout(PortalStore s, string customer) { if (s.Cart(customer).Count == 0) return "<section class='empty'><h1>Your cart is empty.</h1><a class='button' href='/shop'>Browse products</a></section>"; var person = s.Customers.Single(item => item.Id == customer); return $$"""<section class='page-head compact'><p class='eyebrow'>SIMULATED CHECKOUT</p><h1>Finish your order.</h1><p>There is no payment collection in this demo.</p></section><section class='panel form'><form class='stack js-form' data-api='/api/orders' data-order='true'><label>Display name<input name='name' value='{{H(person.Name)}}' required></label><label>Email<input name='email' value='{{H(person.Email)}}' type='email' required></label><label>Delivery city<input name='city' value='{{H(person.City)}}' required></label><label class='check'><input name='isSimulated' type='checkbox' value='true' required>I understand this is a simulated order.</label><button class='button'>Place simulated order</button></form></section>"""; }
static string OrdersPage(HttpContext c, PortalStore s) { var orders = s.Orders.Where(item => Internal(c) || item.CustomerId == Customer(c)).OrderByDescending(item => item.CreatedAt); return $$"""<section class='page-head compact'><p class='eyebrow'>{{(Internal(c) ? "OPERATIONS / ORDERS" : "MY ORDERS")}}</p><h1>{{(Internal(c) ? "Fulfilment at a glance." : "Every order, in one place.")}}</h1></section><section class='table'><table><thead><tr><th>Order</th><th>Customer</th><th>Placed</th><th>Status</th><th>Total</th><th></th></tr></thead><tbody>{{string.Join("", orders.Select(item => $"<tr><td>{item.Id}</td><td>{H(s.Customers.Single(customer => customer.Id == item.CustomerId).Name)}</td><td>{Date(item.CreatedAt)}</td><td>{Badge(item.Status)}</td><td>{Money(item.Total)}</td><td><a class='link' href='/orders/{item.Id}'>View</a></td></tr>"))}}</tbody></table></section>"""; }
static string OrderPage(HttpContext c, Order o) => $$"""<section class='detail'><div><p class='eyebrow'>ORDER / {{o.Id}}</p><h1>{{Badge(o.Status)}}</h1><p>Delivery to {{H(o.City)}} · placed {{Date(o.CreatedAt)}}</p></div>{{(Internal(c) && o.Status is "Confirmed" or "Processing" or "Shipped" ? $"<button class='button advance' data-api='/api/orders/{o.Id}/advance'>Advance fulfilment</button>" : !Internal(c) && o.Status == "Delivered" ? $"<button class='button outline return' data-api='/api/orders/{o.Id}/return-requests'>Request a return</button>" : "")}}</section><section class='two'><article class='panel'><h2>Items</h2>{{string.Join("", o.Lines.Select(line => $"<div class='row'><span>{H(line.Name)} {H(line.Configuration)}</span><span>{line.Quantity} × {Money(line.UnitPrice)}</span></div>"))}}<div class='row total'><span>Total</span><b>{{Money(o.Total)}}</b></div>{{(o.Tracking is null ? "" : $"<p class='notice'>NordicBike Logistics · tracking {H(o.Tracking)}</p>")}}</article><article class='panel'><h2>Order timeline</h2>{{Events(o.Timeline)}}</article></section>""";
static string BikesPage(HttpContext c, PortalStore s) => $$"""<section class='page-head compact'><p class='eyebrow'>MY BIKES</p><h1>Everything that carries you.</h1></section><section class='cards'>{{string.Join("", s.Bikes.Where(item => Internal(c) || item.CustomerId == Customer(c)).Select(item => $"<article class='card'><div class='bike'>{H(item.ProductName[..1])}</div><p class='eyebrow'>{H(item.Registration)}</p><h2>{H(item.ProductName)}</h2><p>{H(item.Serial)}</p><dl><dt>Purchased</dt><dd>{item.Purchased:yyyy-MM-dd}</dd><dt>Service</dt><dd>{H(item.ServiceStatus)}</dd></dl><a class='link' href='/support'>Get support</a></article>"))}}</section><section class='panel form'><p class='eyebrow'>REGISTER A BIKE</p><h2>Purchased elsewhere?</h2><form class='stack js-form' data-api='/api/bikes/registrations' data-redirect='/bikes'><label>Serial number<input name='serial' placeholder='AX3-25A-00417' required></label><label>Purchase date<input name='purchased' type='date' required></label><button class='button'>Request verification</button></form></section>""";
static string CustomerSupport(HttpContext c, PortalStore s) { var orders = s.Orders.Where(item => item.CustomerId == Customer(c)); var bikes = s.Bikes.Where(item => item.CustomerId == Customer(c)); return $$"""<section class='page-head compact'><p class='eyebrow'>SUPPORT</p><h1>We will help you keep moving.</h1><p>support@nordicbike.se · +46 8 555 123 00 · Monday-Friday 09:00-17:00 CET</p></section><section class='two'><article class='panel'><h2>Start a case</h2><form class='stack js-form' data-api='/api/cases' data-case='true'><label>Subject<input name='subject' required></label><label>Topic<select name='topic'><option>Order and delivery</option><option>Product question</option><option>Bike or battery fault</option><option>Warranty and repair</option><option>Return request</option><option>Other</option></select></label><label>Related order<select name='orderId'><option value=''>None</option>{{string.Join("", orders.Select(item => $"<option>{item.Id}</option>"))}}</select></label><label>Related bike<select name='bikeId'><option value=''>None</option>{{string.Join("", bikes.Select(item => $"<option value='{item.Id}'>{H(item.ProductName)} · {H(item.Serial)}</option>"))}}</select></label><label>Description<textarea name='description' required></textarea></label><label>Simulated attachment metadata<input name='attachment' placeholder='photo.jpg (1.2 MB)'></label><button class='button'>Submit case</button></form></article><article class='panel'><h2>Your cases</h2>{{string.Join("", s.Cases.Where(item => item.CustomerId == Customer(c)).OrderByDescending(item => item.UpdatedAt).Select(item => $"<a class='case' href='/support/{item.Id}'>{Badge(item.Status)}<b>{H(item.Subject)}</b><small>{item.Id} · {Date(item.UpdatedAt)}</small></a>"))}}</article></section>"""; }
static string Queue(HttpContext c, PortalStore s, string? q, string? status) { var cases = s.Cases.Where(item => (string.IsNullOrWhiteSpace(q) || Search(s, item).Contains(q, StringComparison.OrdinalIgnoreCase)) && (string.IsNullOrWhiteSpace(status) || item.Status == status)); return $$"""<section class='page-head compact'><p class='eyebrow'>SUPPORT WORKSPACE</p><h1>Keep the next customer moving.</h1><form class='search'><input name='q' value='{{H(q)}}' placeholder='Search case, customer, order or serial'><select name='status'><option value=''>All statuses</option>{{string.Join("", s.Cases.Select(item => item.Status).Distinct().Select(item => $"<option {(item == status ? "selected" : "")}>{H(item)}</option>"))}}</select><button>Filter</button></form></section><section class='table'><table><thead><tr><th>Case</th><th>Customer</th><th>Subject</th><th>Priority</th><th>Status</th><th>Owner</th><th></th></tr></thead><tbody>{{string.Join("", cases.Select(item => $"<tr><td>{item.Id} {(item.Escalated ? "<i>Escalated</i>" : "")}</td><td>{H(s.Customers.Single(customer => customer.Id == item.CustomerId).Name)}</td><td>{H(item.Subject)}</td><td>{Badge(item.Priority)}</td><td>{Badge(item.Status)}</td><td>{H(item.Assignee ?? "Unassigned")}</td><td><a class='link' href='/support/{item.Id}'>Open</a></td></tr>"))}}</tbody></table></section>"""; }
static string CasePage(HttpContext c, PortalStore s, SupportCase item) { var internalView = Internal(c); var person = s.Customers.Single(customer => customer.Id == item.CustomerId); var messages = item.Messages.Where(message => internalView || message.Visibility == "Customer"); var controls = !internalView ? "" : $$"""<article class='panel'><p class='eyebrow'>CASE CONTROLS</p><form class='stack js-form' data-api='/api/cases/{{item.Id}}' data-method='PATCH'><label>Status<select name='status'>{{string.Join("", new[] { "New", "Waiting for customer", "In progress", "Waiting for service center", "Resolved", "Closed" }.Select(value => $"<option {(value == item.Status ? "selected" : "")}>{value}</option>"))}}</select></label><label>Priority<select name='priority'><option>Low</option><option selected>Normal</option><option>High</option></select></label><label>Owner<select name='assignee'><option></option><option>Sofia Nilsson</option><option>Oskar Bergman</option></select></label><label class='check'><input name='escalated' type='checkbox' value='true' {{(item.Escalated ? "checked" : "")}}>Escalated</label><button class='button'>Save case</button></form><form class='stack note js-form' data-api='/api/cases/{{item.Id}}/messages'><input type='hidden' name='internal' value='true'><label>Internal note<textarea name='body' required></textarea></label><button class='button outline'>Add note</button></form><form class='stack note js-form' data-api='/api/cases/{{item.Id}}/service-requests'><label>Service center<select name='center'><option>Stockholm</option><option>Gothenburg</option><option>Malmo</option></select></label><button class='button outline'>Create service request</button></form></article>"""; return $$"""<section class='detail'><div><p class='eyebrow'>SUPPORT CASE / {{item.Id}}</p><h1>{{H(item.Subject)}}</h1><p>{{H(person.Name)}} · {{H(item.Topic)}} · {{Badge(item.Status)}} {{(item.Escalated ? "<i>Escalated</i>" : "")}}</p></div></section><section class='case-grid'><article class='panel'><h2>Conversation</h2>{{string.Join("", messages.Select(message => $"<div class='message {message.Visibility.ToLowerInvariant()}'><b>{H(message.Author)}</b><small>{H(message.Role)} · {Date(message.At)}</small><p>{H(message.Body)}</p></div>"))}}<form class='stack note js-form' data-api='/api/cases/{{item.Id}}/messages'><label>Reply<textarea name='body' required></textarea></label><button class='button'>Send message</button></form></article><aside><article class='panel'><h2>Case context</h2><p>{H(item.Description)}</p><dl><dt>Order</dt><dd>{H(item.OrderId ?? "None")}</dd><dt>Bike</dt><dd>{H(item.BikeId ?? "None")}</dd><dt>Policies</dt><dd>policies/warranty.md<br>policies/escalation.md</dd></dl></article>{{controls}}<article class='panel'><h2>Activity</h2>{{Events(item.Timeline)}}</article></aside></section>"""; }
static string Business(PortalStore s) => $$"""<section class='page-head compact'><p class='eyebrow'>BUSINESS OPERATIONS</p><h1>The current demo picture.</h1><p>Operational demo metrics, not accounting records.</p></section><section class='metrics'><article><p>Confirmed revenue</p><strong>{{Money(s.Orders.Where(item => item.Status is not "Cancelled" and not "Returned").Sum(item => item.Total))}}</strong></article><article><p>Orders</p><strong>{{s.Orders.Count}}</strong></article><article><p>Return requests</p><strong>{{s.Orders.Count(item => item.Status == "Return requested")}}</strong></article><article><p>Open cases</p><strong>{{s.Cases.Count(item => item.Status is not "Resolved" and not "Closed")}}</strong></article></section><section class='two'><article class='panel'><h2>Fulfilment states</h2>{{string.Join("", s.Orders.GroupBy(item => item.Status).Select(group => $"<div class='row'><span>{H(group.Key)}</span><b>{group.Count()}</b></div>"))}}</article><article class='panel'><h2>Top products</h2>{{string.Join("", s.Orders.SelectMany(item => item.Lines).GroupBy(item => item.Name).OrderByDescending(group => group.Count()).Take(5).Select(group => $"<div class='row'><span>{H(group.Key)}</span><b>{group.Sum(item => item.Quantity)} units</b></div>"))}}</article></section>""";
static string Diagnostics(PortalStore s, string? correlation, string? entity) { var events = s.Audits.Where(item => (string.IsNullOrWhiteSpace(correlation) || item.CorrelationId.Contains(correlation, StringComparison.OrdinalIgnoreCase)) && (string.IsNullOrWhiteSpace(entity) || item.EntityId.Contains(entity, StringComparison.OrdinalIgnoreCase))).Take(50); return $$"""<section class='page-head compact'><p class='eyebrow'>INTERNAL DIAGNOSTICS</p><h1>Trace the useful evidence.</h1><p>Audit events connect to safe console logs. Message bodies are intentionally absent.</p><form class='search'><input name='correlation' value='{{H(correlation)}}' placeholder='Correlation ID'><input name='entity' value='{{H(entity)}}' placeholder='Order, case or service ID'><button>Filter</button></form></section><section class='table'><table><thead><tr><th>When</th><th>Action</th><th>Entity</th><th>Actor</th><th>Correlation</th><th>Safe detail</th></tr></thead><tbody>{{string.Join("", events.Select(item => $"<tr><td>{Date(item.At)}</td><td>{H(item.Action)}</td><td>{H(item.EntityId)}</td><td>{H(item.Actor)}</td><td><code>{H(item.CorrelationId)}</code></td><td>{H(item.Detail)}</td></tr>"))}}</tbody></table></section>"""; }
public sealed record CartInput(string ProductId, int Quantity, string? Configuration);
public sealed record CheckoutInput(string Name, string Email, string City, bool IsSimulated);
public sealed record BikeInput(string Serial, DateOnly Purchased);
public sealed record CaseInput(string Subject, string Description, string Topic, string? OrderId, string? BikeId, string? Attachment);
public sealed record MessageInput(string Body, bool Internal);
public sealed record CaseUpdate(string? Status, string? Priority, string? Assignee, bool? Escalated);
public sealed record ServiceInput(string Center, string? State);

public static class PortalConfig
{
	public static readonly Dictionary<string, (string Name, string Customer)> Roles = new()
	{
		["anna"] = ("Anna Karlsson", "NB-CUST-10041"),
		["support"] = ("Support agent", ""),
		["lead"] = ("Support lead", ""),
		["business"] = ("Business operations", "")
	};

	public static readonly HashSet<string> RepairStates = ["Awaiting item", "Received", "Diagnosing", "Repairing", "Ready for return", "Completed"];
}